version: '3.4'

services:
  authserver:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "50648:80"
    volumes:
      - ~/Https:/root/.aspnet/https:ro
      - ~/UserSecrets:/root/.microsoft/usersecrets:ro
      
  resourceserver:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "50649:80"
    volumes:
      - ~/Https:/root/.aspnet/https:ro
      - ~/UserSecrets:/root/.microsoft/usersecrets:ro
      - pictures:/data/pictures

  postgresDB:
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: "AuthServerDB"
    ports:
      - "5433:5432"
    restart: always
    volumes:
      - /docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - pictures:/data/pictures

volumes:
  pictures: