version: '3.4'

services:
  authserver:
    container_name: 'authServer'
    image: ${DOCKER_REGISTRY-}authserver
    build:
      context: .
      dockerfile: AuthServer/Dockerfile

  resourceserver:
    container_name: 'resourceServer'
    image: ${DOCKER_REGISTRY-}resource_server
    build:
      context: .
      dockerfile: ResourceServer/Dockerfile

  postgresDB:
    container_name: 'postgresDB'
    image: postgres
    build:
      context: .
      dockerfile: Dockerfile-DB