version: '3.4'

services:
  authserver:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=44343
    ports:
      - "50648:80"
      - "44343:443"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
    networks:
      - "authNetwork"
    depends_on:
      - "postgresDB"

  postgresDB:
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: "AuthServerDB"
    ports:
      - "5433:5432"
    restart: always
    networks:
      - "authNetwork"

networks:
  authNetwork:
    driver: bridge
