version: '3.4'

services:
  authserver:
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "50648:80"
    volumes:
      - ~/Https:/root/.aspnet/https:ro
      - ~/UserSecrets:/root/.microsoft/usersecrets:ro
      - /var/log/apapp/as:/var/log/apapp
      
  resourceserver:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - AuthSrvContainerUrl=http://authServer:80
      - ResourceSrvUrl=http://167.99.60.13:50649
      - ConnectionStrings__DefaultConnection=Host=postgresDB;Username=postgres;Password=admin;Database=TrueHomeDB
      - ConnectionStrings__MigrationConnection=Host=postgresDB;Username=postgres;Password=admin
    ports:
      - "50649:80"
    volumes:
      - ~/Https:/root/.aspnet/https:ro
      - ~/UserSecrets:/root/.microsoft/usersecrets:ro
      - /data/pictures:/data/pictures
      - /var/log/apapp/rs:/var/log/apapp
      - /data/pictures:/data/pictures

  postgresDB:
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: "AuthServerDB"
    ports:
      - "5433:5432"
    restart: always
    volumes:
      - /docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - /data/pictures:/data/pictures