version: '3.4'

services:
  authserver:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=44343
    ports:
      - "50648:80"
      - "44343:443"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
    networks:
      - "authNetwork"
    depends_on:
      - "postgresDB"
      
  resourceserver:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=44344
    ports:
      - "50649:80"
      - "44344:443"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  postgresDB:
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: "AuthServerDB"
    ports:
      - "5433:5432"
    restart: always
    volumes:
      - ./postgresDB_scripts:/docker-entrypoint-initdb.d
      - postgres:/var/lib/postgresql/data
    networks:
      - "authNetwork"
      
networks:
  authNetwork:
    driver: bridge

volumes:
  postgres: